services:
  caddy:
    image: caddy:latest
    container_name: ratecourse-caddy
    hostname: ratecourse-caddy
    restart: on-failure:3
    ports:
      - "0.0.0.0:443:443"
      - "0.0.0.0:80:80"
    networks:
      - ratecourse-network
    volumes:
      - ./Caddyfile-production:/etc/caddy/Caddyfile
      - ratecourse-caddy-ssl-data:/data

volumes:
  ratecourse-caddy-ssl-data:
    driver: local
    external: false
    name: ratecourse-caddy-ssl-data

networks:
  ratecourse-network:
    driver: bridge
    external: true
    name: ratecourse-network