ktor:
  deployment:
    port: ${RECOMMENDATION_PORT}
    host: "0.0.0.0"

  application:
    modules:
      - com.gnomeshift.recommendationservice.RecommendationServiceApplicationKt.module

database:
  url: ${DB_URL}
  user: ${DB_USER}
  password: ${DB_PASSWORD}

kafka:
  bootstrapServers: "localhost:9092"
  groupId: "recommendation-service-group"
  topic: "ratings"
  autoOffsetReset: "earliest"

service:
  name: "recommendation-service"